/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yzuveehmaccnbsvnfiuf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6dXZlZWhtYWNjbmJzdm5maXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MDY0MzksImV4cCI6MjA3NjM4MjQzOX0.SEke1-orgp-tn4HySwBx7FHDvpiVaOzBNI3Wepz7YnY"